### PR TITLE
feat: auto-completion for sub-commands

### PR DESCRIPTION
**Pull request by Ephigenia**
# Purpose

- adds general code for being able to add auto-completion logic to sub-commands

# Description of Change

- [x] integrate tabtab library and test in zsh shell
- [x] integration install / uninstall auto-completion as sub-command
- [x] auto-completion for all sub-commands:
	- [x] amend
	- [x] config
	- [x] customers
	- [x] ~~delete~~
	- [x] list
	- [x] new
	- [x] ~~open~~
	- [x] projects
	- [x] services
	- [x] ~~start~~
	- [x] ~~stop~~
	- [x] users
- [ ] add test for auto-completion
- [x] update documentation
- [ ] add gif animation(s) to illustrate the ease of auo-completion

### CODE REVIEW

**Comment by Ephigenia** [comment]
@chufgard would you be interested in testing this auto-completion feature? this also improves the usability of `mite new`

**Comment by musikpirat** [comment]
Great feature! But Is it possible to make the auto-complete case-insensitive? I started with a wrong case and thought the feature might be not working. :)

There is also a typo in mite-autocomplete.js. "unintall" instead of "uninstall"

**Comment by chufgard** [comment]
Great feature! But Is it possible to make the auto-complete case-insensitive? I started with a wrong case and thought the feature might be not working. :)

There is also a typo in mite-autocomplete.js. "unintall" instead of "uninstall"

**Comment by Ephigenia** [comment]
@chufgard thanks for finding that typo!

Concerning the case-sensitivity of the auto-completion … that might depend on the shell. I’m using ZSH shell and I’m having a customer let’s say it’s called "Expertgroup", when I start typing `mite new "my new note" expert` and then hit TAB it uppercases the "e" to "E" and auto-completes the whole partial to "Expertgroup". So at least for ZSH it seems to be case-insensitive.

Maybe you can give a more concrete example for me to test with?

**Comment by Ephigenia** [comment]
@chufgard I’ll merge this now as I want to add some more commands which also need to have auto-completion and not to get to many conflicts. Please add a new issue for the "development" version if the problem still remains. Thanks!

**Pull request merged**
