### PR TITLE
Added cli code to mite_new

### PR DESCRIPTION
**Pull request by chufgard**
# Purpose
With this new function it is possible to create a new mite entry without having to scroll through a list of possibilities. Is is also possible to create aliases to make booking even easier.

Example:

`mite new cool_project internal_service 60 "Enhanced mite-cli"`

Books 60 minutes on cool_project/internal_service with the comment "Enhanced mite-cli"

Using this alias
`alias mite_cool_stuff='mite new cool_project internal_service'`
it is possible to create new entries with the command
`mite_cool_stuff 60 "Enhanced mite-cli"`

As last parameter a date can be given. If is omitted, today is used.

### CODE REVIEW

**Comment by Ephigenia** [comment]
I reviewed the PR and would like to change it a tiny bit. I already started with it and hopefully finish it till tomorrow.

**Comment by chufgard** [comment]
Do whatever you think is needed to improve the code. :)

**Comment by chufgard** [comment]
Is there any way I can assist you?

**Comment by Ephigenia** [comment]
I’ve merge a slightly modified version of this feature. The "note" is now the first parameter so that it also can be used for the interactive mode like before:

     mite new "my custom note"

which will then run the interactive mode. Hope that’s okay too ❓

**Comment by musikpirat** [comment]
Look good - go for it!

**Pull request merged**
